Repository DhanushNehru/Python-Scripts, pull requests merged in 2022-10, with the labels that each got.

#22 Script for taking an image
  Image Capture/README.md
  Image Capture/take_pictures_from_webcam.py
  README.md
Labels: hacktoberfest

#41 added website_blocker
  Website Blocker/mac/Website_Blocker.py
  Website Blocker/read.me
Labels: hacktoberfest

#9 Readme revamp
  README.md
Labels: help wanted, documentation, hacktoberfest

#46 Image Crop
  .DS_Store
  Crop_Images/README.md
  Crop_Images/crop.py
  Crop_Images/icon.png
  Crop_Images/output screenshot.png
Labels: hacktoberfest, good first issue

#57 Text tand Image to PDF sc
  Image_Text to PDF/img.jpg
  Image_Text to PDF/input.txt
  Image_Text to PDF/readme.md
  Image_Text to PDF/script.py
Labels: enhancement, hacktoberfest

#69 Removed .DS_Store, updated .gitignore with basic template
  .DS_Store
  .gitignore
Labels: hacktoberfest, good first issue

#72 Added turtle scripts
  Turtle_Art/Prompt_Based/benzene.py
  Turtle_Art/Prompt_Based/tkinterName.py
  Turtle_Art/Prompt_Based/windowsLogo.py
  Turtle_Art/README.md
  Turtle_Art/Xsquare.py
  Turtle_Art/art2.py
  Turtle_Art/art4.py
  Turtle_Art/art5.py
  Turtle_Art/scenery.py
  Turtle_Art/sunflowerGood.py
Labels: hacktoberfest

#78 Updated paths to be relative, removed credentials, added sample csv file
  Automating Emails/Birthday-Manager.py
  Automating Emails/birthday.csv
Labels: enhancement, hacktoberfest

#92 Added Arrange It Folder
  Arrange It/README.md
  Arrange It/arrangeit.py
Labels: hacktoberfest

#94 added csv to excel converter
  CSVToExcel/csv_excel.py
Labels: hacktoberfest

#99 Currency_calculator
  currency_script/currency_calculator.py
Labels: hacktoberfest

#102 added a python simulation
  planetSimulation/main.py
Labels: hacktoberfest

#103 TIK-TAC-TOE
  TIK-TAC-TOE/Game.py
Labels: hacktoberfest

#108 Snake-Water-Gun (issue #95)
  Snake-Water-Gun/snake-water-gun.py
Labels: hacktoberfest

#110 Create Virtual Painter Directory
  Keylogger/keylogger.py
  Virtual_Painter/tools.png
  Virtual_Painter/virtual_paint_app.py
Labels: hacktoberfest

#113 Added Image to gif py script
  Image-to-gif/README.md
  Image-to-gif/imageTogif.py
  README.md
Labels: hacktoberfest

#114 Added my script in readme
  README.md
Labels: hacktoberfest
